[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"

[build]
rustflags = [
"--cfg=web_sys_unstable_apis"
]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-weak_framework Metal -weak_framework MetalPerformanceShaders"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-weak_framework Metal -weak_framework MetalPerformanceShaders"]
